/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import static controller.ControllerEntradas.fechaActual;




/**
 *
 * @author lgfon
 */
public class frmManteEntradas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMante
     */
    public frmManteEntradas() {
        initComponents();
        setResizable(false);
        //AGREGAR TITULO A FORMULARIO
        setTitle("Mantenimiento Entradas");
            lbl1.setVisible(false);
            lbl2.setVisible(false);
            lbl3.setVisible(false);
            lbl4.setVisible(false);
            lbl5.setVisible(false);
            lbl7.setVisible(false);
            lbl8.setVisible(false);
            lbl9.setVisible(false);
            lbl10.setVisible(false);
            lbl11.setVisible(false);
            lbl12.setVisible(false);
            lbl13.setVisible(false);
            lbl14.setVisible(false);
            lblVisita2.setVisible(false);
            lblTotal2.setVisible(false);
            SpCantidad1.setVisible(false);
            SpCantidad.setVisible(false);
            SpMayores.setVisible(false);
            SpMenores.setVisible(false);
            SpBebes.setVisible(false);
            btnPagar2.setVisible(false);
            btnPagar1.setVisible(false);
            btnVolver2.setVisible(false);
            jSeparator2.setVisible(false);
            jSeparator3.setVisible(false);
            jSeparator1.setVisible(false);
            jSeparator4.setVisible(false);
            CbAtracciones.setVisible(false);
            jdFecha.setVisible(false);
            jdFecha1.setVisible(false);
            tblEntradas.setVisible(false);
            lblFechaVenta.setText(fechaActual());
            lblVenta.setVisible(false);
            lblFechaVenta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CbPase = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        SpMayores = new javax.swing.JSpinner();
        SpMenores = new javax.swing.JSpinner();
        SpBebes = new javax.swing.JSpinner();
        lbl4 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblVisita2 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnVolver2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnPagar2 = new javax.swing.JButton();
        jdFecha = new com.toedter.calendar.JDateChooser();
        lbl14 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblVenta = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CbAtracciones = new javax.swing.JComboBox<>();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        SpCantidad1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntradas = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btnPagar1 = new javax.swing.JButton();
        lbl5 = new javax.swing.JLabel();
        jdFecha1 = new com.toedter.calendar.JDateChooser();
        lbl11 = new javax.swing.JLabel();
        SpCantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantenimiento de Entradas");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        CbPase.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        CbPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPaseActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Mayores de 18 años:");

        lbl2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Entre 3 - 17 años:");

        lbl3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Menores de 3 años:");

        SpMayores.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        SpMayores.setToolTipText("");

        SpMenores.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        SpBebes.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        lbl4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Fecha de Visita:");

        lbl7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("Cantidad de entradas:");

        lbl8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setText("Total:");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        lblVisita2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        btnVolver2.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnVolver2.setText("VOLVER");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2btnVolverActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setText("Desea comprar un pase especial?");

        btnPagar2.setBackground(new java.awt.Color(204, 204, 204));
        btnPagar2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnPagar2.setText("PAGAR");

        lbl14.setText("** DISPONIBLE");

        lbl12.setText("LAS  ATRACCIONES");

        lbl13.setText("TODAS");

        btnIngresar.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblVenta.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenta.setText("Fecha de Venta:");

        lblFechaVenta.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbl14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbPase)
                        .addGap(143, 143, 143)
                        .addComponent(btnIngresar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPagar2)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl4, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl3, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(lblVenta)
                                            .addGap(76, 76, 76)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFechaVenta)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblVisita2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(SpMenores, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(SpBebes)
                                            .addComponent(lblTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SpMayores)
                                            .addComponent(jdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbPase)
                    .addComponent(jLabel11)
                    .addComponent(btnIngresar))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl14)
                    .addComponent(lbl12)
                    .addComponent(lbl13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpMayores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpBebes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3))
                        .addGap(18, 18, 18)
                        .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnPagar2)
                .addGap(35, 35, 35)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl7)
                    .addComponent(lblVisita2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl8)
                    .addComponent(lblTotal2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVenta)
                    .addComponent(lblFechaVenta))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        CbAtracciones.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        CbAtracciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carrusel", "Pulpo", "Pacuare", "Rueda de Chicago", "Splash", "Reventazon", "Carros Chocones", "MiniTorre", "Abejones", "Tren Electrico", "TacitasLocas" }));
        CbAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbAtraccionesActionPerformed(evt);
            }
        });

        lbl9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl9.setText("Atracciones");

        lbl10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("Cantidad de personas:");

        SpCantidad1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        tblEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntradasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntradas);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setToolTipText("");

        btnPagar1.setBackground(new java.awt.Color(204, 204, 204));
        btnPagar1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnPagar1.setText("PAGAR");

        lbl5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("Fecha de Visita:");

        lbl11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("Cantidad de atracciones:");

        SpCantidad.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPagar1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl5)
                                        .addGap(77, 77, 77)
                                        .addComponent(jdFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl11)
                                        .addGap(18, 18, 18)
                                        .addComponent(SpCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SpCantidad)
                                    .addComponent(CbAtracciones, 0, 206, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(CbAtracciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl11)
                    .addComponent(SpCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl5)
                    .addComponent(jdFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPagar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver2btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmPrincipal P = new frmPrincipal();
    }//GEN-LAST:event_btnVolver2btnVolverActionPerformed

    private void tblEntradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntradasMouseClicked
        // TODO add your handling code here:.
    }//GEN-LAST:event_tblEntradasMouseClicked

    private void CbPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPaseActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_CbPaseActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
            if (CbPase.isSelected()) {
            lbl1.setVisible(true);
            lbl2.setVisible(true);
            lbl3.setVisible(true);
            lbl4.setVisible(true);
            lbl7.setVisible(true);
            lbl8.setVisible(true);
            lbl13.setVisible(true);
            lbl12.setVisible(true);
            lbl14.setVisible(true);
            btnPagar2.setVisible(true);
            btnVolver2.setVisible(true);
            jSeparator1.setVisible(true);
            jSeparator3.setVisible(true);
            jSeparator4.setVisible(true);
            lblTotal2.setVisible(true);
            lblVisita2.setVisible(true);
            jdFecha.setVisible(true);
            SpMayores.setVisible(true);
            SpMenores.setVisible(true);
            SpBebes.setVisible(true);
            tblEntradas.setVisible(true);
            lblVenta.setVisible(true);
            lblFechaVenta.setVisible(true);
            ////////////////////////////
            lbl5.setVisible(false);
            lbl9.setVisible(false);
            lbl10.setVisible(false);
            lbl11.setVisible(false);
            CbAtracciones.setVisible(false);
            SpCantidad1.setVisible(false);
            SpCantidad.setVisible(false);
            btnPagar1.setVisible(false);
            jSeparator2.setVisible(false);
            jdFecha1.setVisible(false);

        } else {
            lbl5.setVisible(true);
            lbl7.setVisible(true);
            lbl8.setVisible(true);
            lbl9.setVisible(true);
            lbl10.setVisible(true);
            lbl11.setVisible(true);
            CbAtracciones.setVisible(true);
            SpCantidad1.setVisible(true);
            SpCantidad.setVisible(true);
            btnPagar1.setVisible(true);
            btnVolver2.setVisible(true);
            jSeparator3.setVisible(true);
            jSeparator4.setVisible(true);
            jSeparator2.setVisible(true);
            lblTotal2.setVisible(true);
            lblVisita2.setVisible(true);
            jdFecha1.setVisible(true);
            tblEntradas.setVisible(true);
            lblVenta.setVisible(true);
            lblFechaVenta.setVisible(true);
            ////////////////////////////
            lbl1.setVisible(false);
            lbl2.setVisible(false);
            lbl3.setVisible(false);
            lbl4.setVisible(false);
            lbl13.setVisible(false);
            lbl12.setVisible(false);
            lbl14.setVisible(false);
            btnPagar2.setVisible(false);
            jdFecha.setVisible(false);
            SpMayores.setVisible(false);
            SpMenores.setVisible(false);
            SpBebes.setVisible(false);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void CbAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbAtraccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbAtraccionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CbAtracciones;
    public javax.swing.JCheckBox CbPase;
    public javax.swing.JSpinner SpBebes;
    public javax.swing.JSpinner SpCantidad;
    public javax.swing.JSpinner SpCantidad1;
    public javax.swing.JSpinner SpMayores;
    public javax.swing.JSpinner SpMenores;
    private javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnPagar1;
    public javax.swing.JButton btnPagar2;
    public javax.swing.JButton btnVolver2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public com.toedter.calendar.JDateChooser jdFecha;
    public com.toedter.calendar.JDateChooser jdFecha1;
    public javax.swing.JLabel lbl1;
    public javax.swing.JLabel lbl10;
    public javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    public javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    public javax.swing.JLabel lbl2;
    public javax.swing.JLabel lbl3;
    public javax.swing.JLabel lbl4;
    public javax.swing.JLabel lbl5;
    public javax.swing.JLabel lbl7;
    public javax.swing.JLabel lbl8;
    public javax.swing.JLabel lbl9;
    public javax.swing.JLabel lblFechaVenta;
    public javax.swing.JLabel lblTotal2;
    public javax.swing.JLabel lblVenta;
    public javax.swing.JLabel lblVisita2;
    public javax.swing.JTable tblEntradas;
    // End of variables declaration//GEN-END:variables
}
